<a href="https://colab.research.google.com/github/trevorgdobson/colab/blob/master/Colab_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

# IRIS Dataset
# https://warwick.ac.uk/fac/sci/moac/people/students/peter_cock/r/iris_lm/
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head()

# Create X numpy array
X = np.array(iris.drop(['species'], axis=1))
print(type(X), X.shape)

Y = iris['species']
# print Y.unique()
# encode class values as integers, then as binary columns
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
encoder = LabelEncoder()
encoder.fit(Y)
Y = to_categorical(encoder.transform(Y))
print encoded_Y[:5]

(<type 'numpy.ndarray'>, (150, 4))
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [0]:
model = Sequential()
# Version 0 - 4 nodes 1 layer
# model.add(Dense(4, input_shape=(4,), activation='relu'))
# Version 1 - 20 nodes 1 layer
# model.add(Dense(20, input_shape=(4,), activation='relu'))
# Version 2 - 100 nodes x 2 layers
model.add(Dense(100, input_shape=(4,), activation='relu'))
model.add(Dense(100, activation='relu'))

# Output layer
model.add(Dense(3, activation='softmax'))

model.compile(loss='binary_crossentropy',
              optimizer='adam', metrics=['accuracy'])

# NOTES:
# For this dataset, there is some randomness in the accuracy (98.6%
# or 99.1%), but increasing the node count or layer count doesn't 
# seem to improve results.


In [102]:
# Fit model
model.fit(X, Y, epochs=150, batch_size=10,  verbose=0)
# evaluate the model
scores = model.evaluate(X, encoded_Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

# print some example predictions
print model.predict(X)[:10]

150/150 [==============================] - 0s 74us/step

acc: 99.11%
[[9.9999988e-01 1.7379297e-07 5.0070484e-13]
 [9.9999905e-01 9.5587870e-07 6.5247547e-12]
 [9.9999940e-01 6.5082673e-07 3.9437741e-12]
 [9.9999690e-01 3.0562305e-06 2.5115481e-11]
 [9.9999976e-01 1.9795188e-07 5.4162848e-13]
 [9.9999940e-01 5.4011753e-07 9.9907832e-13]
 [9.9999809e-01 1.8985478e-06 1.1423846e-11]
 [9.9999952e-01 4.8173018e-07 1.8134295e-12]
 [9.9999499e-01 5.0309545e-06 6.3073262e-11]
 [9.9999928e-01 6.6503031e-07 3.5863083e-12]]


In [0]:
## Simple graph of structure of network

# from IPython.display import SVG
# from keras.utils.vis_utils import model_to_dot

# SVG(model_to_dot(model).create(prog='dot', format='svg'))

In [0]:
### Plot Accuracy Over Training Time by Epoch

# import matplotlib.pyplot as plt

# history = model.fit(X, Y, validation_split=0.25, epochs=50, batch_size=16, verbose=1)

# # Plot training & validation accuracy values
# plt.plot(history.history['acc'])
# plt.plot(history.history['val_acc'])
# plt.title('Model accuracy')
# plt.ylabel('Accuracy')
# plt.xlabel('Epoch')
# plt.legend(['Train', 'Test'], loc='upper left')
# plt.show()

# # Plot training & validation loss values
# plt.plot(history.history['loss'])
# plt.plot(history.history['val_loss'])
# plt.title('Model loss')
# plt.ylabel('Loss')
# plt.xlabel('Epoch')
# plt.legend(['Train', 'Test'], loc='upper left')
# plt.show()